### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ClaireWangGoForIt** [martincooper/scala-datatable#4]
Hello! Thanks for your work of datatable! I have a problem to install it. My build.sbt is:
name := "scala"

version := "0.1"

scalaVersion := "2.12.2"

libraryDependencies += "com.github.martincooper" %% "scala-datatable" % "0.8.0"

My sbt is 1.8.0 and I use them in IntelliJ IDEA. I cannot install datatable in this way. The message is:sbt 'scala' project refresh failed.

Thanks a lot in advance for your help!

**Comment by ClaireWangGoForIt** [comment]
In addition, is it necessary to use sbt 0.13.0? I can find minimum of 0.13.5

**Comment by martincooper** [comment]
Hey! Yes, it certainly should work with all the latest versions of Scala / SBT etc.

To test, using IntelliJ I just updated to the latest version of everything (Scala 2.12.4), SBT (1.0.3), and created a new project with the following in my build.sbt...

```
name := "ScalaTest"
version := "0.1"
scalaVersion := "2.12.4"
libraryDependencies += "com.github.martincooper" %% "scala-datatable" % "0.8.0"
```

and Scala DataTable imported fine with no errors. You say you are using version 1.8.0 of SBT which is odd as I can only see 1.0.3 as the latest version http://www.scala-sbt.org/download.html

**Comment by ClaireWangGoForIt** [comment]
Thanks! Now my libraries list like this
![library](https://user-images.githubusercontent.com/12323398/33252786-2020664e-d37b-11e7-974b-448f98370fd3.PNG)
But I still can not import this package 
![import](https://user-images.githubusercontent.com/12323398/33252826-59f86308-d37b-11e7-889e-3284aedf291b.PNG)
I am sorry that I am new to Scala and thanks a lot for your help!

**Comment by martincooper** [comment]
You need to fully namespace your imports, so something like this would work for a single class...

```
import com.github.martincooper.datatable.DataTable
```

Or for multiple...

```
import com.github.martincooper.datatable.{ DataColumn, DataTable, DataTableException, GenericColumn }
```

or for all...

```
import com.github.martincooper.datatable._
```

etc.

**Comment by ClaireWangGoForIt** [comment]
Thanks a lot for your reply but I still cannot solve the problem.
`scala> import com.github.martincooper.datatable.DataTable
<console>:14: error: object github is not a member of package com
       import com.github.martincooper.datatable.DataTable`
 Did I miss something important?
![whole](https://user-images.githubusercontent.com/12323398/33256493-3f128c8c-d38d-11e7-9caa-d27922eb63a7.PNG)

**Comment by martincooper** [comment]
Try running...

```
sbt clean compile
```

**Comment by ClaireWangGoForIt** [comment]
sorry...I don't know how to run this command...And I reopen the project but still cannot import the package
![whole](https://user-images.githubusercontent.com/12323398/33257054-b3fc531e-d38f-11e7-9e33-e430384fb0d4.PNG)

**Comment by ClaireWangGoForIt** [comment]
If I type 'clean compile' in the SBT Shell, I will get some errors as below

![whole](https://user-images.githubusercontent.com/12323398/33257143-06e65e1c-d390-11e7-82db-20c260779619.PNG)

**Comment by martincooper** [comment]
In SBT shell, just enter ```clean```, then ```compile``` if the first step works.

**Comment by ClaireWangGoForIt** [comment]
sorry I tried but it still doesn't work and thanks a lot for your help!
![whole](https://user-images.githubusercontent.com/12323398/33258596-1d208cca-d395-11e7-9a8a-ba4ed3803254.PNG)
![sbt](https://user-images.githubusercontent.com/12323398/33258607-234293d2-d395-11e7-9ed3-4dbcf716936c.PNG)
![import](https://user-images.githubusercontent.com/12323398/33258609-26e57b12-d395-11e7-8b87-12d632f72cfb.PNG)

**Comment by martincooper** [comment]
This is related to your Scala / environment / project setup and I can't really help you any further. I would suggest you google "object is not a member of package" and there a number of pages which highlight the error and a number of things you can do to try and resolve it. Thanks

**Comment by ClaireWangGoForIt** [comment]
Ok! Thanks for your help!
